import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useContext } from "react";
import { UserContext } from "../context";
export default function Home() {

  const [state, setState] = useContext(UserContext);


  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <div>
    <h1>hello
    {JSON.stringify(state)}


    </h1>
   </div>


    </div>
  )
}
