import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useContext } from "react";
import { UserContext } from "../context";

import { useEffect, useState } from 'react';
import io from 'socket.io-client';

let socket = null;

export default function Home() {

  const [state, setState] = useContext(UserContext);

  useEffect(() => {
    fetch('/api/socket').finally(() => {
        socket = io();

        socket.emit('getStore');

        socket.on('returnTest', () => {
            alert("Works!");
        });
    });
}, []);

function testEmit() {
    if (!socket) return;

    socket.emit('test')
}





  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <div>
    <h1>hello
 



    </h1>
   </div>


    </div>
  )
}
