import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { useContext } from "react";
import { UserContext } from "../context";
import {toast} from "react-toastify";
import { server } from "../config/url.js";

import { useEffect, useState } from 'react';
import io from 'socket.io-client';



export default function Home() {

  const [state, setState] = useContext(UserContext);
  const [message, setMessage] = useState('');

  const [socketis, setSocket] = useState(null)
  const [text, setText] = useState("")
  const [messages, setMessages] = useState([])
const [reciver, setReciver] = useState("")

//   useEffect(() => {
//     fetch('/api/socket').finally(() => {
//         socket = io();

//         socket.emit('getStore');

//         socket.on('returnTest', () => {
//             alert("Works!");
//         });
//     });
// }, []);

useEffect(() => {

  // const socket = io('/api/socket');
  // //socket.on('message', handleMessage)

  // setSocket(socket)


  fetch(`${server}/api/socket`).finally(() => {
   
 const   socket = io();
 setSocket(socket)
       
    socket.emit("notification", {
      
      message: `my name is ${state.name} `,
    });

    
          
        });



  

}, [])




const sendMessage = () => {


      socketis.emit('message-send', message);
   console.log(message)

   socketis.on('recive-msg', (msg) => {
    toast.success(msg)
    console.log('reciver ==>',msg)
    setReciver(msg)

   // setMessages([...messages, message])
  }
  )

}




  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

   <div>
    <h1>hello

      <input 
          value={message}
          onChange={(e) => setMessage(e.target.value)}
      type="text"
      />
 

<button
onClick={sendMessage}
>send Message</button>


    </h1>
   </div>


    </div>
  )
}
